# Generated by Django 4.1 on 2022-08-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprescribe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrescribeMed',
        ),
    ]
